name: Setup
description: Common environment setup

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v6
      with:
        node-version: 24.x
    - uses: actions/cache@v5
      id: cache
      with:
        path: '**/node_modules'
        key: npm-v3-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      run: npm ci
      shell: bash
      if: steps.cache.outputs.cache-hit != 'true'
    - name: Install Foxar
      run: |
        curl -L https://up.foxar.dev/ | bash
        export PATH="$HOME/.foxar/bin:$PATH"
        foxarup
      shell: bash
    - name: Install ylem
      run: |
        curl -L https://github.com/core-coin/ylem/releases/download/1.1.9/ylem-linux-x86_64 -o $HOME/.foxar/bin/ylem
        chmod +x $HOME/.foxar/bin/ylem
        ylem --version
      shell: bash
